imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_imports = true
comment_width = 100
