imports_layout = "HorizontalVertical"
format_code_in_doc_comments = true
match_block_trailing_comma = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
normalize_doc_attributes = true
overflow_delimited_expr = true
blank_lines_upper_bound = 2
reorder_imports = true
comment_width = 100
